// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD08lVOmZSzXk_M1PLzdMFwjK5geTC6OqE',
    appId: '1:512224492743:web:f8d2cb2459d5a0dff152e2',
    messagingSenderId: '512224492743',
    projectId: 'candleledger-cee65',
    authDomain: 'candleledger-cee65.firebaseapp.com',
    storageBucket: 'candleledger-cee65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK1imz2HONYcpOQMQJB8qo0R7P6KpCF1k',
    appId: '1:512224492743:android:831793252616d723f152e2',
    messagingSenderId: '512224492743',
    projectId: 'candleledger-cee65',
    storageBucket: 'candleledger-cee65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJP6cVFYn-3s3XV82QkBLBtVc5FPLpqs',
    appId: '1:512224492743:ios:d108898aa667dfe5f152e2',
    messagingSenderId: '512224492743',
    projectId: 'candleledger-cee65',
    storageBucket: 'candleledger-cee65.firebasestorage.app',
    androidClientId: '512224492743-58uislbqqv58tr4e098ejj946jap9d19.apps.googleusercontent.com',
    iosClientId: '512224492743-44a798lo3to1rha6be7vtk2kc6fsad3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.candleLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJP6cVFYn-3s3XV82QkBLBtVc5FPLpqs',
    appId: '1:512224492743:ios:d108898aa667dfe5f152e2',
    messagingSenderId: '512224492743',
    projectId: 'candleledger-cee65',
    storageBucket: 'candleledger-cee65.firebasestorage.app',
    androidClientId: '512224492743-58uislbqqv58tr4e098ejj946jap9d19.apps.googleusercontent.com',
    iosClientId: '512224492743-44a798lo3to1rha6be7vtk2kc6fsad3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.candleLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD08lVOmZSzXk_M1PLzdMFwjK5geTC6OqE',
    appId: '1:512224492743:web:cd7e8743a3b51f30f152e2',
    messagingSenderId: '512224492743',
    projectId: 'candleledger-cee65',
    authDomain: 'candleledger-cee65.firebaseapp.com',
    storageBucket: 'candleledger-cee65.firebasestorage.app',
  );
}
